#!/bin/bash
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBTACH -n 2
#SBATCH -t 07:00:00
#SBATCH -J Genome_Assembly_PacBIO_2022-03-30-13:15
#SBATCH -o Genome_Assemlby_PacBIO-2022-03-30.log 
#SBATCH -e Genome_Assembly_PacBIO-2022-03-30.err 

#load modules
module load bioinfo-tools samtools/0.1.19 bwa
module load canu
export SRCDIR=$HOME/samuel50


#Command
cd home/samuel50/Genome_Assembly

canu \
 -p  -d Genomic_data \
 genomeSize=2.4m \
 -pacbio pacbio./home/samuel50/Genom_Analysis/Genomic_Data/*
