#!/bin/bash
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core -n 2
#SBATCH -t 08:00:00
#SBATCH -J Prokka-2
#SBACTH --reservation=uppmax2022-2-5_8

#load modules
module load bioinfo-tools samtools/0.1.19 bwa prokka

prokka \
--outdir /home/samuel50/Genom_Analysis/Prokka/result \
--addgenes --cpus 2 --kingdom Bacteria --species Enterococcus_faecium --strain E745 --prefix mygenome \
/domus/h1/samuel50/Genom_Analysis/Genomic_Data/PACBIO/Complete_Assembly/Complete_Assembly_PACKBIO_30-03-16.38/Genome_assembly_Pacbio-30-03-16.38.contigs.fasta

